#ifndef ERROR_CODES_H
#define ERROR_CODES_H

typedef enum {
    ERR_OK = 0,  // No error

    /* merge.h */
    ERR_MERGE_FIRST_FILE_OPEN = 1001,
    ERR_MERGE_SECOND_FILE_OPEN,
    ERR_MERGE_OFFSET,
    ERR_MERGE_WRITE,

    /* replace.h */
    ERR_REPLACE_INVALID_POSITION = 1101,
    ERR_REPLACE_FILE_OPEN,
    ERR_REPLACE_DATA_FILE_OPEN,
    ERR_REPLACE_PWRITE,
    ERR_REPLACE_PREAD,

    /* copy_file.h */
    ERR_COPY_FILE_OPEN = 1201,
    ERR_COPY_FILE_CREATE,
    ERR_COPY_FILE_PART_COPY,
    ERR_COPY_FILE_GENERAL,
    ERR_COPY_DIR_OPEN,
    ERR_COPY_STAT_FAILED,
    ERR_COPY_DIR_CANNOT_COPY,
    ERR_COPY_SRC_HASH_FAIL,
    ERR_COPY_DST_HASH_FAIL,
    ERR_COPY_NO_INPUT_FILE,
    ERR_COPY_NO_OUTPUT_PATH,
    ERR_COPY_INPUT_FILE_OPEN,
    ERR_COPY_SAME_FILE_INPUT,
    ERR_COPY_SAME_FILE_OUTPUT,
    ERR_COPY_FILE_NOT_ALLOWED,
    ERR_COPY_DIR_CANNOT_COPY_2,
    ERR_COPY_DST_HASH_FAIL_2,
    ERR_COPY_DIR_MKDIR_FAIL,
    ERR_COPY_DIR_SRC_PATH_INFO,
    ERR_COPY_DIR_RECURSIVE_FAIL,
    ERR_COPY_FILE_FULL_FAIL,

    /* cli_parser.h */
    ERR_CLI_NUMBER_OUT_OF_RANGE = 1301,
    ERR_CLI_INVALID_NUMBER,
    ERR_CLI_ZERO_OR_NEGATIVE_SPLIT,
    ERR_CLI_INVALID_ARGUMENT,

    /* select_and_merge.h */
    ERR_SELECT_TOO_MANY_PARTS = 1401,
    ERR_SELECT_INVALID_PART_VALUE,
    ERR_SELECT_FILE_OPEN,
    ERR_SELECT_FILE_CREATE,
    ERR_SELECT_PREAD,
    ERR_SELECT_PWRITE,

    /* sha256.h */
    ERR_SHA_FILE_OPEN = 1501,
    ERR_SHA_CTX_NEW,
    ERR_SHA_DIGEST_INIT,
    ERR_SHA_DIGEST_UPDATE,
    ERR_SHA_FILE_READ,
    ERR_SHA_DIGEST_FINAL,

    /* insert.h */
    ERR_INSERT_FILE_OPEN = 1601,
    ERR_INSERT_DATA_FILE_OPEN,
    ERR_INSERT_MKSTEMP,
    ERR_INSERT_INVALID_PART_LOCATION,
    ERR_INSERT_PWRITE,
    ERR_INSERT_PREAD,
    ERR_INSERT_FTRUNCATE,

    /* split.h */
    ERR_SPLIT_FILE_OPEN = 1701,
    ERR_SPLIT_PART_CREATE,
    ERR_SPLIT_PREAD,
    ERR_SPLIT_PWRITE,

    /* Generic */
    ERR_UNKNOWN = 1999

} ErrorCode;

#endif // ERROR_CODES_H